# Generated by Anaconda 43.44
# Keyboard layouts
keyboard --vckeymap=es --xlayouts='es'
# System language
lang es_ES.UTF-8

%packages
@^server-product-environment
@container-management
@domain-client
@guest-agents
@server-hardware-support

%end

# System authorization information
authselect enable-feature with-fingerprint

# Run the Setup Agent on first boot
firstboot --enable

# Generated using Blivet version 3.12.1
ignoredisk --only-use=vda
autopart
# Partition clearing information
clearpart --none --initlabel

# System timezone
timezone Europe/Madrid --utc

# Root password
user --groups=wheel --name=usuario --password=contrasenaacambiar/ --iscrypted --gecos="usuario"
